service: asdfa-tools
frameworkVersion: '2'

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    region: us-west-2
    versionFunctions: false
    profile: asdfa
    memorySize: 128 # don't need much
    apiGateway:
        minimumCompressionSize: 200
    #websocketsApiName:
    websocketsApiRouteSelectionExpression: $request.body.action



custom:
    serverless-offline:
        noPrependStageInUrl: true

package:
    patterns:
        - '!**'
        - 'node_modules/**' # will only include non-dev dependencies
        - '!node_modules/.bin/**' # ...maybe
        - 'build/**'
        - 'server/**'

functions:
    webResource:
        handler: server/handler.webResource
        events:
            - httpApi: '*'
            #ideally we'd just use '*' for all, but serverless-offline has issues
            - httpApi:
                method: GET
                path: /
            - httpApi:
                method: GET
                path: /{any}
            - httpApi:
                method: GET
                path: /{any1}/{any2}

    time:
        handler: server/time.time
        events:
            - websocket:
                route: time
                routeResponseSelectionExpression: $default

    # wsConnect:
    #     handler: server/wsHandler.connect
    #     events:
    #         - websocket:
    #             route: $connect
    #         - websocket:
    #             route: $disconnect
    # wsMessage:
    #     handler: server/wsHandler.message
    #     events:
    #         - websocket:
    #             route: $default
    #         - websocket:
    #             route: $disconnect
